language: python
sudo: false
python:
    - "3.6"
install:
    - pip install -U pip wheel setuptools
    - pushd ~
    - git clone --depth 1 https://github.com/pretix/pretix.git
    - cd pretix/src
    - pip3 install -Ur requirements.txt -r requirements/dev.txt
    - python setup.py develop
    - make all compress
    - popd
script:
    - flake8 .
    - isort -c -rc .
cache:
    directories:
        - $HOME/.cache/pip
addons:
    apt:
        packages:
            - enchant
            - myspell-de-de
            - aspell-en
